server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jbdc:postgresql://localhost:5332/customer
    username: lightcodese
    password: password
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet